# Generated by Django 3.2.3 on 2021-05-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='URL_view_name',
            field=models.CharField(default='basic_edit_account', max_length=256),
        ),
    ]
