# Generated by Django 3.2.3 on 2021-05-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicUser', '0002_basicuser_url_view_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='URL_view_name',
            field=models.CharField(default='api_edit_account', max_length=256),
        ),
    ]
