# Generated by Django 3.2.3 on 2021-06-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicUser', '0003_alter_basicuser_url_view_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuser',
            name='URL_view_name',
        ),
    ]
