FROM python:3.9.1

ENV PYTHONUNBUFFERED 1
WORKDIR /code

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        musl-dev python3-dev build-essential python-dev
RUN pip install --upgrade pip

COPY requirements.txt /code/
RUN pip3 install -r requirements.txt
COPY . /code/

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
