version: "3.9"

services:
  api:
    environment:
        - DJANGOMODE="API"
    build: ./
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5432"]
        interval: 30s
        timeout: 10s
        retries: 5
