FROM python:3.9.1

ENV PYTHONUNBUFFERED 1
WORKDIR /code

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
        musl-dev python3-dev build-essential python-dev
RUN pip install --no-cache-dir --upgrade pip  && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /code/
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . /code/

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
