name: D++ Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload Documentation to Wiki
      - uses: cmbrose/github-docs-to-wiki@v0.24
        with:
          githubToken: ${{ secrets.GITHUBTOKEN }}
          rootDocsFolder: "/Doc"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Standard drop-in approach that should work for most people.
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"


      - name: Commit documentation changes
        run: |
          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      # ===============================
